//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovay
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ЗаявкаНаТовара.
    /// </summary>
    // *** Start programmer edit section *** (ЗаявкаНаТовара CustomAttributes)

    // *** End programmer edit section *** (ЗаявкаНаТовара CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ЗаявкаНаТовара : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovay.ОбщаяяДокументация fОбщаяяДокументация;
        
        // *** Start programmer edit section *** (ЗаявкаНаТовара CustomMembers)

        // *** End programmer edit section *** (ЗаявкаНаТовара CustomMembers)

        
        /// <summary>
        /// ЗаявкаНаТовара.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация CustomAttributes)
        [PropertyStorage(new string[] {
                "ОбщаяяДокументация"})]
        [NotNull()]
        public virtual IIS.Kursovay.ОбщаяяДокументация ОбщаяяДокументация
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Get start)

                // *** End programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Get start)
                IIS.Kursovay.ОбщаяяДокументация result = this.fОбщаяяДокументация;
                // *** Start programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Get end)

                // *** End programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Set start)

                // *** End programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Set start)
                this.fОбщаяяДокументация = value;
                // *** Start programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Set end)

                // *** End programmer edit section *** (ЗаявкаНаТовара.ОбщаяяДокументация Set end)
            }
        }
    }
}
