//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovay
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ОбщаяяДокументация.
    /// </summary>
    // *** Start programmer edit section *** (ОбщаяяДокументация CustomAttributes)

    // *** End programmer edit section *** (ОбщаяяДокументация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class ОбщаяяДокументация : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (ОбщаяяДокументация CustomMembers)

        // *** End programmer edit section *** (ОбщаяяДокументация CustomMembers)

    }
}
