//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovay
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар на складе.
    /// </summary>
    // *** Start programmer edit section *** (ТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (ТоварНаСкладе CustomAttributes)
    [AutoAltered()]
    [Caption("Товар на складе")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварНаСкладеE", new string[] {
            "Количество as \'Количество\'"})]
    public class ТоварНаСкладе : ICSSoft.STORMNET.DataObject
    {
        
        private string fКоличество;
        
        private IIS.Kursovay.Склад fСклад;
        
        // *** Start programmer edit section *** (ТоварНаСкладе CustomMembers)

        // *** End programmer edit section *** (ТоварНаСкладе CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Количество CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Количество CustomAttributes)
        [StrLen(255)]
        public virtual string Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Get start)
                string result = this.fКоличество;
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Количество Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Количество Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovay.Склад.
        /// </summary>
        // *** Start programmer edit section *** (ТоварНаСкладе.Склад CustomAttributes)

        // *** End programmer edit section *** (ТоварНаСкладе.Склад CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Склад"})]
        public virtual IIS.Kursovay.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Get start)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Get start)
                IIS.Kursovay.Склад result = this.fСклад;
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Get end)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Set start)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (ТоварНаСкладе.Склад Set end)

                // *** End programmer edit section *** (ТоварНаСкладе.Склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварНаСкладеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварНаСкладеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварНаСкладеE", typeof(IIS.Kursovay.ТоварНаСкладе));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТоварНаСкладе.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТоварНаСкладе CustomAttributes)
    public class DetailArrayOfТоварНаСкладе : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovay.DetailArrayOfТоварНаСкладе members)

        // *** End programmer edit section *** (IIS.Kursovay.DetailArrayOfТоварНаСкладе members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТоварНаСкладе by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТоварНаСкладе.
        /// </summary>
        public DetailArrayOfТоварНаСкладе(IIS.Kursovay.Склад fСклад) : 
                base(typeof(ТоварНаСкладе), ((ICSSoft.STORMNET.DataObject)(fСклад)))
        {
        }
        
        public IIS.Kursovay.ТоварНаСкладе this[int index]
        {
            get
            {
                return ((IIS.Kursovay.ТоварНаСкладе)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovay.ТоварНаСкладе dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
